# Site settings
title:       The New Gazette - RSS Archive
description: The New Gazette provides curated and unbiased local news — no more, no less. This archive stores our publications for future access by the communities we serve.
subtitle:    "Preserving local news for future readers"
baseurl:     ""
company_url: "https://newgazette.co"
email:       editor@newgazette.co
language:    en-us
author:      The New Gazette
copyright:   "CC BY 4.0"

# Data
# google_analytics: UA-XXXXX-Y

# Social
twitter_link: https://twitter.com/thenewgazette

# Collections
collections:
  publications:
  hsv-monthly:
  hsv-insider:

# RSS
rss:
  hsv-monthly:
    - name: HSV Monthly Brief
      link: hsv-monthly.rss
  hsv-insider:
    - name: HSV Insider
      link: hsv-insider.rss

# Markdown settings
markdown: kramdown

# Sass settings
sass:
  add_charset: true
  sass_dir: assets/sass
  style: :compressed

# Build settings
exclude:
  - package.json
  - README.md
  - CNAME
  - assets/sass

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-sitemap